[tool.poetry]
name = "etl-01"
version = "0.1.0"
description = ""
authors = ["Márcio Mota <marcio_mota@usp.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
